from __future__ import annotations

import importlib.util
import io
import json
import tarfile
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / "scripts" / "validate_cvm_submission.py"


def _load_module():
    spec = importlib.util.spec_from_file_location("validate_cvm_submission", SCRIPT)
    if spec is None or spec.loader is None:
        raise ImportError(SCRIPT)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


class ValidateCVMSubmissionTests(unittest.TestCase):
    def test_generated_artifact_hash_check_accepts_matching_tables_and_figures(self) -> None:
        module = _load_module()
        data_hash = "abc123"
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            tables = root / "tables"
            figures = root / "figures"
            tables.mkdir()
            figures.mkdir()
            for name in module.REQUIRED_TABLES:
                (tables / name).write_text(
                    f"% generated by test; data_hash={data_hash}\n",
                    encoding="utf-8",
                )
            for name in module.REQUIRED_FIGURES:
                (figures / name).write_bytes(b"%PDF-1.5\n")

            with patch.object(module, "_mutool_info", return_value=f"Subject(data_hash={data_hash})"):
                failures = module._generated_artifact_failures(
                    data_hash=data_hash,
                    table_dirs=(tables,),
                    figure_dirs=(figures,),
                )

        self.assertEqual([], failures)

    def test_generated_artifact_hash_check_reports_mismatches(self) -> None:
        module = _load_module()
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            tables = root / "tables"
            figures = root / "figures"
            tables.mkdir()
            figures.mkdir()
            for name in module.REQUIRED_TABLES:
                (tables / name).write_text("% generated by test; data_hash=old\n", encoding="utf-8")
            for name in module.REQUIRED_FIGURES:
                (figures / name).write_bytes(b"%PDF-1.5\n")

            with patch.object(module, "_mutool_info", return_value="Subject(data_hash=old)"):
                failures = module._generated_artifact_failures(
                    data_hash="new",
                    table_dirs=(tables,),
                    figure_dirs=(figures,),
                )

        self.assertIn(f"generated_table_hash_mismatch:{tables / module.REQUIRED_TABLES[0]}", failures)
        self.assertIn(
            f"generated_figure_hash_mismatch:{figures / module.REQUIRED_FIGURES[0]}",
            failures,
        )

    def test_release_hygiene_accepts_clean_public_surface(self) -> None:
        module = _load_module()
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            (root / "README.md").write_text("WOD2Sim release notes\n", encoding="utf-8")
            (root / "wod2sim.pdf").write_bytes(b"%PDF-1.5\n")
            (root / "paper" / "cvm").mkdir(parents=True)
            (root / "paper" / "cvm" / "main.tex").write_text(
                "Contract-based integration paper\n",
                encoding="utf-8",
            )

            failures = module._release_hygiene_failures(
                repo_root=root,
                canonical_paper=root / "wod2sim.pdf",
            )

        self.assertEqual([], failures)

    def test_release_hygiene_reports_sensitive_or_weak_public_text(self) -> None:
        module = _load_module()
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            token = "hf_" + ("A" * 20)
            fixture = "spot" + "light_reflex"
            unsupported_claim = "we " + "outperform baselines"
            (root / "README.md").write_text(
                "\n".join(
                    [
                        token,
                        "/home/" + "amdev" + "/private",
                        fixture,
                        unsupported_claim,
                    ]
                ),
                encoding="utf-8",
            )
            (root / "wod2sim.pdf").write_bytes(b"%PDF-1.5\n")

            failures = module._release_hygiene_failures(
                repo_root=root,
                canonical_paper=root / "wod2sim.pdf",
            )

        self.assertIn("public_hygiene:huggingface_token:README.md", failures)
        self.assertIn("public_hygiene:private_home_path:README.md", failures)
        self.assertIn("public_hygiene:legacy_smoke_fixture:README.md", failures)
        self.assertIn("public_hygiene:outperformance_claim:README.md", failures)

    def test_release_hygiene_reports_duplicate_manuscript_pdfs(self) -> None:
        module = _load_module()
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            (root / "README.md").write_text("WOD2Sim release notes\n", encoding="utf-8")
            (root / "wod2sim.pdf").write_bytes(b"%PDF-1.5\n")
            duplicate = root / "paper" / "cvm" / "paper.pdf"
            duplicate.parent.mkdir(parents=True)
            duplicate.write_bytes(b"%PDF-1.5\n")

            failures = module._release_hygiene_failures(
                repo_root=root,
                canonical_paper=root / "wod2sim.pdf",
            )

        self.assertIn("duplicate_manuscript_pdf:paper/cvm/paper.pdf", failures)

    def test_release_hygiene_reports_public_archive_text_leaks(self) -> None:
        module = _load_module()
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            archive_path = root / "artifacts" / "cvm" / "results" / "public" / "support-bundle.tar.gz"
            archive_path.parent.mkdir(parents=True)
            payload = json.dumps({"path": "/home/" + "amdev" + "/private"}).encode()
            with tarfile.open(archive_path, "w:gz") as archive:
                info = tarfile.TarInfo("demo/run-audit.json")
                info.size = len(payload)
                archive.addfile(info, io.BytesIO(payload))

            failures = module._release_hygiene_failures(
                repo_root=root,
                canonical_paper=root / "wod2sim.pdf",
            )

        self.assertIn(
            "public_hygiene_archive:private_home_path:"
            "artifacts/cvm/results/public/support-bundle.tar.gz:demo/run-audit.json",
            failures,
        )


if __name__ == "__main__":
    unittest.main()
