from __future__ import annotations

import importlib.util
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / "scripts" / "validate_sii2027_submission.py"


def _load_module():
    spec = importlib.util.spec_from_file_location("validate_sii2027_submission", SCRIPT)
    if spec is None or spec.loader is None:
        raise ImportError(SCRIPT)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


class ValidateSII2027SubmissionTests(unittest.TestCase):
    def test_generated_artifact_hash_check_accepts_matching_tables_and_figures(self) -> None:
        module = _load_module()
        data_hash = "abc123"
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            tables = root / "tables"
            figures = root / "figures"
            tables.mkdir()
            figures.mkdir()
            for name in module.REQUIRED_TABLES:
                (tables / name).write_text(
                    f"% generated by test; data_hash={data_hash}\n",
                    encoding="utf-8",
                )
            for name in module.REQUIRED_FIGURES:
                (figures / name).write_bytes(b"%PDF-1.5\n")

            with patch.object(module, "_mutool_info", return_value=f"Subject(data_hash={data_hash})"):
                failures = module._generated_artifact_failures(
                    data_hash=data_hash,
                    table_dirs=(tables,),
                    figure_dirs=(figures,),
                )

        self.assertEqual([], failures)

    def test_generated_artifact_hash_check_reports_mismatches(self) -> None:
        module = _load_module()
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            tables = root / "tables"
            figures = root / "figures"
            tables.mkdir()
            figures.mkdir()
            for name in module.REQUIRED_TABLES:
                (tables / name).write_text("% generated by test; data_hash=old\n", encoding="utf-8")
            for name in module.REQUIRED_FIGURES:
                (figures / name).write_bytes(b"%PDF-1.5\n")

            with patch.object(module, "_mutool_info", return_value="Subject(data_hash=old)"):
                failures = module._generated_artifact_failures(
                    data_hash="new",
                    table_dirs=(tables,),
                    figure_dirs=(figures,),
                )

        self.assertIn(f"generated_table_hash_mismatch:{tables / module.REQUIRED_TABLES[0]}", failures)
        self.assertIn(
            f"generated_figure_hash_mismatch:{figures / module.REQUIRED_FIGURES[0]}",
            failures,
        )


if __name__ == "__main__":
    unittest.main()
